# Foreman Installer Configuration Template
# This file contains common configuration options for offline Foreman installation
# Copy this file and modify as needed for your environment

# Foreman Configuration
foreman:
  # Admin user settings
  admin_password: "CHANGE_ME_TO_SECURE_PASSWORD"
  
  # Database configuration
  db_type: "postgresql"  # Options: postgresql, mysql, sqlite
  db_host: "localhost"
  db_port: 5432
  db_name: "foreman"
  db_user: "foreman"
  db_password: "CHANGE_ME_TO_SECURE_PASSWORD"
  
  # Web interface settings
  server_ssl_cert: "/etc/foreman/ssl_cert.pem"
  server_ssl_key: "/etc/foreman/ssl_key.pem"
  server_ssl_ca: "/etc/foreman/ssl_ca.pem"
  
  # Email configuration
  email_delivery_method: "smtp"
  email_smtp_address: "localhost"
  email_smtp_port: 25
  email_smtp_domain: "example.com"
  email_smtp_authentication: "none"
  email_smtp_user_name: ""
  email_smtp_password: ""

# Foreman Proxy Configuration
foreman_proxy:
  # Proxy settings
  dhcp: true
  dns: true
  tftp: true
  puppet: true
  puppetca: true
  
  # Network settings
  dhcp_interface: "eth0"
  dns_interface: "eth0"
  tftp_interface: "eth0"
  
  # SSL configuration
  ssl_cert: "/etc/foreman-proxy/ssl_cert.pem"
  ssl_key: "/etc/foreman-proxy/ssl_key.pem"
  ssl_ca: "/etc/foreman-proxy/ssl_ca.pem"
  
  # OAuth settings
  oauth_consumer_key: "CHANGE_ME_TO_RANDOM_KEY"
  oauth_consumer_secret: "CHANGE_ME_TO_RANDOM_SECRET"
  
  # Foreman URL
  foreman_url: "https://foreman.example.com"

# Puppet Configuration
puppet:
  # Puppet server settings
  server: true
  server_foreman: true
  server_foreman_url: "https://foreman.example.com"
  server_foreman_ssl_ca: "/etc/foreman-proxy/ssl_ca.pem"
  server_foreman_ssl_cert: "/etc/foreman-proxy/ssl_cert.pem"
  server_foreman_ssl_key: "/etc/foreman-proxy/ssl_key.pem"
  
  # Puppet agent settings
  agent: true
  
  # PuppetDB settings
  server_puppetdb: true
  server_puppetdb_server: "localhost"
  server_puppetdb_port: 8081

# Apache Configuration
apache:
  # Virtual host settings
  server_name: "foreman.example.com"
  server_aliases: ["foreman"]
  
  # SSL settings
  ssl: true
  ssl_cert: "/etc/foreman/ssl_cert.pem"
  ssl_key: "/etc/foreman/ssl_key.pem"
  ssl_ca: "/etc/foreman/ssl_ca.pem"
  
  # Passenger settings
  passenger: true
  passenger_ruby: "/usr/bin/ruby"

# Database Configuration
postgresql:
  # PostgreSQL server settings
  server: true
  
  # Database settings
  server_foreman_db_name: "foreman"
  server_foreman_db_user: "foreman"
  server_foreman_db_password: "CHANGE_ME_TO_SECURE_PASSWORD"
  
  # Connection settings
  server_foreman_db_host: "localhost"
  server_foreman_db_port: 5432

# TFTP Configuration
tftp:
  # TFTP server settings
  server: true
  
  # Directory settings
  root: "/var/lib/tftpboot"
  
  # Network settings
  interface: "eth0"

# DHCP Configuration
dhcp:
  # DHCP server settings
  server: true
  
  # Network settings
  interface: "eth0"
  
  # Subnet configuration
  subnet: "192.168.1.0"
  netmask: "255.255.255.0"
  gateway: "192.168.1.1"
  range: "192.168.1.100 192.168.1.200"

# DNS Configuration
dns:
  # DNS server settings
  server: true
  
  # Network settings
  interface: "eth0"
  
  # Zone configuration
  zone: "example.com"
  reverse: "1.168.192.in-addr.arpa"
  
  # Forwarders
  forwarders: ["8.8.8.8", "8.8.4.4"]

# Logging Configuration
logging:
  # Log level
  level: "INFO"
  
  # Log file locations
  foreman_log: "/var/log/foreman"
  proxy_log: "/var/log/foreman-proxy"
  puppet_log: "/var/log/puppet"

# Security Configuration
security:
  # SELinux settings
  selinux: true
  
  # Firewall settings
  firewall: true
  
  # SSL/TLS settings
  ssl_version: "TLSv1.2"
  ssl_ciphers: "HIGH:!aNULL:!MD5"

# Performance Configuration
performance:
  # Worker processes
  workers: 2
  
  # Database connections
  db_pool: 5
  
  # Cache settings
  cache_store: "file_store"
  cache_path: "/tmp/foreman_cache"

# Monitoring Configuration
monitoring:
  # Service monitoring
  monitor_services: true
  
  # Health checks
  health_check_interval: 300
  
  # Alerting
  email_alerts: false
  snmp_alerts: false
